ARG FROM_IMAGE=ubuntu:18.04

FROM $FROM_IMAGE

ARG ARG_GOSU_VERSION

ARG ARG_JDK_VERSION

ARG ARG_MVN_VERSION

ARG ARG_SCALA_VERSION

ARG ARG_SCALA_PACKAGE_SHA1

ENV GOSU_VERSION=${ARG_GOSU_VERSION:-1.14} \
    JDK_VERSION=${ARG_JDK_VERSION:-11} \
    MVN_VERSION=${ARG_MVN_VERSION:-3.8.4} \
    SCALA_VERSION=${ARG_SCALA_VERSION:-2.12.12} \
    SCALA_PACKAGE_SHA1=${ARG_SCALA_PACKAGE_SHA1:-ef2c2aec4954a0a7c6a24e8283e16acba35ac78f} \
    PATH="${PATH}:/opt/apache-maven-${ARG_MVN_VERSION:-3.8.4}/bin" \
    JAVA_HOME=/usr/lib/jvm/temurin-${ARG_JDK_VERSION:-11}-jdk-amd64

MAINTAINER infrastructure@zensystem.io

SHELL ["/bin/bash", "-c"]

RUN set -euxo pipefail \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends apt-transport-https apt-utils \
      ca-certificates curl dirmngr git gnupg2 jq pigz wget \
    && if ! command -v gosu &> /dev/null; then \
      dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')" \
      && wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch" \
      && wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc" \
      && export GNUPGHOME="$(mktemp -d)" \
      && ( gpg2 --batch --keyserver hkps://keys.openpgp.org --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 || \
       gpg2 --batch --keyserver hkps://keyserver.ubuntu.com:443 --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 || \
       gpg2 --batch --keyserver pgp.mit.edu --recv-key B42F6819007F00F88E364FD4036A9C25BF357DD4 ) \
      && gpg2 --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu \
      && ( gpgconf --kill dirmngr || true ) \
      && ( gpgconf --kill gpg-agent || true ) \
      && rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc \
      && unset GNUPGHOME \
      && chmod +x /usr/local/bin/gosu \
      && gosu nobody true; \
    fi \
    && export GNUPGHOME="$(mktemp -d)" \
    && curl -sSf https://packages.adoptium.net/artifactory/api/gpg/key/public > key.asc \
    && gpg2 --batch --with-subkey-fingerprint --keyid-format LONG key.asc 2> /dev/null | grep -q 3B04D753C9050D9A5D343F39843C48A565F8F04B \
    && mkdir -p /usr/share/keyrings/ \
    && gpg2 --dearmor --output /usr/share/keyrings/adoptium-archive-keyring.gpg key.asc \
    && rm key.asc \
    && ( gpgconf --kill dirmngr || true ) \
    && ( gpgconf --kill gpg-agent || true ) \
    && rm -rf "$GNUPGHOME" \
    && unset GNUPGHOME \
    && echo "deb [signed-by=/usr/share/keyrings/adoptium-archive-keyring.gpg] https://packages.adoptium.net/artifactory/deb $(grep '^deb' /etc/apt/sources.list | head -n1 | \
      awk '{print $3}') main" > /etc/apt/sources.list.d/adoptium.list \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends temurin-$JDK_VERSION-jdk \
    && scala_file_name=scala-${SCALA_VERSION}.deb \
    && wget -P /tmp "https://scala-lang.org/files/archive/${scala_file_name}" \
    && echo "${SCALA_PACKAGE_SHA1} /tmp/${scala_file_name}" | sha1sum --check \
    && dpkg -i "/tmp/${scala_file_name}" \
    && mvn_archive=apache-maven-$MVN_VERSION-bin.tar.gz \
    && mvn_asc=${mvn_archive}.asc \
    && wget -P /tmp "https://downloads.apache.org/maven/maven-$(cut -d. -f1 <<< "$MVN_VERSION")/$MVN_VERSION/binaries/$mvn_archive" \
    && wget -P /tmp "https://downloads.apache.org/maven/maven-$(cut -d. -f1 <<< "$MVN_VERSION")/$MVN_VERSION/binaries/$mvn_asc" \
    && export GNUPGHOME="$(mktemp -d)" \
    && curl -sSf https://downloads.apache.org/maven/KEYS | gpg2 --batch --import \
    && gpg2 --batch --verify /tmp/$mvn_asc /tmp/$mvn_archive \
    && ( gpgconf --kill dirmngr || true ) \
    && ( gpgconf --kill gpg-agent || true ) \
    && rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc \
    && unset GNUPGHOME \
    && tar -C /opt -xzf /tmp/$mvn_archive \
    && apt-get -y clean \
    && apt-get -y autoclean \
    && rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*.deb /tmp/* \
    && echo 'PATH="'"$PATH"'"' > /etc/environment
