ARG FROM_IMAGE=ubuntu:18.04

FROM $FROM_IMAGE

ARG ARG_GOSU_VERSION

ARG ARG_JDK_VERSION

ARG ARG_MVN_VERSION

ENV GOSU_VERSION=${ARG_GOSU_VERSION:-1.14} \
    JDK_VERSION=${ARG_JDK_VERSION:-11} \
    MVN_VERSION=${ARG_MVN_VERSION:-3.8.4} \
    PATH="${PATH}:/opt/apache-maven-${ARG_MVN_VERSION:-3.8.4}/bin" \
    JAVA_HOME=/usr/lib/jvm/temurin-${ARG_JDK_VERSION:-11}-jdk-amd64

MAINTAINER infrastructure@zensystem.io

SHELL ["/bin/bash", "-c"]

RUN set -euxo pipefail \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends apt-transport-https apt-utils \
      ca-certificates curl dirmngr gnupg2 jq pigz wget \
    && if ! command -v gosu &> /dev/null; then \
      dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')" \
      && wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch" \
      && wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc" \
      && export GNUPGHOME="$(mktemp -d)" \
      && ( gpg2 --batch --keyserver hkps://keys.openpgp.org --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 || \
       gpg2 --batch --keyserver hkps://keyserver.ubuntu.com:443 --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 || \
       gpg2 --batch --keyserver pgp.mit.edu --recv-key B42F6819007F00F88E364FD4036A9C25BF357DD4 ) \
      && gpg2 --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu \
      && ( gpgconf --kill dirmngr || true ) \
      && ( gpgconf --kill gpg-agent || true ) \
      && rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc \
      && unset GNUPGHOME \
      && chmod +x /usr/local/bin/gosu \
      && gosu nobody true; \
    fi \
    && curl -sSf https://packages.adoptium.net/artifactory/api/gpg/key/public | apt-key add - \
    && echo "deb https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' \
      /etc/os-release) main" > /etc/apt/sources.list.d/adoptium.list \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends temurin-$JDK_VERSION-jdk \
    && mvn_archive=apache-maven-$MVN_VERSION-bin.tar.gz \
    && mvn_asc=${mvn_archive}.asc \
    && wget -P /tmp "https://downloads.apache.org/maven/maven-$(cut -d. -f1 <<< "$MVN_VERSION")/$MVN_VERSION/binaries/$mvn_archive" \
    && wget -P /tmp "https://downloads.apache.org/maven/maven-$(cut -d. -f1 <<< "$MVN_VERSION")/$MVN_VERSION/binaries/$mvn_asc" \
    && export GNUPGHOME="$(mktemp -d)" \
    && curl -sSf https://downloads.apache.org/maven/KEYS | gpg2 --batch --import \
    && gpg2 --batch --verify /tmp/$mvn_asc /tmp/$mvn_archive \
    && ( gpgconf --kill dirmngr || true ) \
    && ( gpgconf --kill gpg-agent || true ) \
    && rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc \
    && unset GNUPGHOME \
    && tar -C /opt -xzf /tmp/$mvn_archive \
    && apt-get -y clean \
    && apt-get -y autoclean \
    && rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*.deb /tmp/* \
    && echo 'PATH="'"$PATH"'"' > /etc/environment
