ARG FROM_IMAGE=ubuntu:18.04

FROM $FROM_IMAGE

ARG ARG_GOSU_VERSION

ARG ARG_RUST_TOOLCHAIN

ARG ARG_RUST_CROSS_TARGETS

ARG ARG_RUST_COMPONENTS

ARG ARG_CARGO_AUDIT_VERSION_OLD_RUST

ARG ARG_CARGO_AUDIT_VERSION_NEW_RUST_MIN=1.63.0

ARG CARGO_HOME=/opt/rust/cargo

ENV GOSU_VERSION=${ARG_GOSU_VERSION:-1.16} \
    RUST_TOOLCHAIN=${ARG_RUST_TOOLCHAIN:-stable} \
    RUST_CROSS_TARGETS=${ARG_RUST_CROSS_TARGETS:-x86_64-pc-windows-gnu,x86_64-apple-darwin} \
    RUST_COMPONENTS=${ARG_RUST_COMPONENTS:-rust-src} \
    RUSTUP_HOME=/opt/rust/rustup \
    PATH="${PATH}:/opt/rust/cargo/bin"

MAINTAINER infrastructure@zensystem.io

SHELL ["/bin/bash", "-c"]

RUN set -euxo pipefail \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends apt-utils \
      build-essential ca-certificates curl dirmngr gcc-mingw-w64-x86-64 git gnupg2 jq \
      libssl-dev pigz pkg-config protobuf-compiler llvm clang wget \
    && if ! command -v gosu &> /dev/null; then \
      dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')" \
      && wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch" \
      && wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc" \
      && export GNUPGHOME="$(mktemp -d)" \
      && ( gpg2 --batch --keyserver hkps://keys.openpgp.org --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 || \
       gpg2 --batch --keyserver hkps://keyserver.ubuntu.com:443 --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 || \
       gpg2 --batch --keyserver pgp.mit.edu --recv-key B42F6819007F00F88E364FD4036A9C25BF357DD4 ) \
      && gpg2 --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu \
      && ( gpgconf --kill dirmngr || true ) \
      && ( gpgconf --kill gpg-agent || true ) \
      && rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc \
      && unset GNUPGHOME \
      && chmod +x /usr/local/bin/gosu \
      && gosu nobody true; \
    fi \
    && curl https://sh.rustup.rs -sSf | bash -s -- -y --default-toolchain none --profile default --no-modify-path \
    && rustup default $RUST_TOOLCHAIN \
    && for target in $(tr "," "\n" <<< "$RUST_CROSS_TARGETS"); do \
      rustup target add --toolchain $RUST_TOOLCHAIN $target; \
    done \
    && for component in $(tr "," "\n" <<< "$RUST_COMPONENTS"); do \
      rustup component add $component; \
    done \
    && mkdir -p /{root,etc/skel}/.cargo \
    && { \
      echo '[target.x86_64-pc-windows-gnu]'; \
      echo 'linker = "x86_64-w64-mingw32-gcc"'; \
      echo 'ar = "x86_64-w64-mingw32-gcc-ar"'; \
    } | tee -a /{root,etc/skel}/.cargo/config > /dev/null \
    && rust_ver="$(rustc --version | cut -d ' ' -f 2)" \
    && if dpkg --compare-versions "${rust_ver}" "lt" "${ARG_CARGO_AUDIT_VERSION_NEW_RUST_MIN}"; then \
      CARGO_AUDIT_VERSION="${ARG_CARGO_AUDIT_VERSION_OLD_RUST}" \
      && git clone --single-branch --branch cargo-audit/v${CARGO_AUDIT_VERSION} https://github.com/rustsec/rustsec /root/rustsec \
      && cd /root/rustsec/cargo-audit \
      && cargo build --release \
      && cd && cp -a /root/rustsec/target/release/cargo-audit /opt/rust/cargo/bin/cargo-audit \
      && rm -rf /root/rustsec; \
    else \
      cargo install cargo-audit \
      && CARGO_AUDIT_VERSION="$(/opt/rust/cargo/bin/cargo-audit --version | cut -d ' ' -f2)"; \
    fi \
    && apt-get -y clean \
    && apt-get -y autoclean \
    && rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*.deb /tmp/* \
    && sed -i '/PATH=/d' /etc/environment \
    && echo 'PATH="'"$PATH"'"' >> /etc/environment \
    && echo "CARGO_AUDIT_VERSION=${CARGO_AUDIT_VERSION}" >> /etc/environment
