os: linux
dist: focal
language: generic
services:
  - docker

env:
  global:
    - DOCKER_ORG=zencash
    - IMAGE_NAME=sc-ci-base
    - GOSU_VERSION=1.12
    - RUST_CROSS_TARGETS=x86_64-pc-windows-gnu
    - JDK_JVM=hotspot
    - MVN_VERSION=3.8.1
  jobs:
    - BASE_IMAGE=ubuntu:bionic FLAVORS=rust-1.42.0 COMBINE='rust-1.42.0;jdk-8,jdk-11,jdk-16'
    - BASE_IMAGE=ubuntu:bionic FLAVORS=rust-1.51.0 COMBINE='rust-1.51.0;jdk-8,jdk-11,jdk-16'
    - BASE_IMAGE=ubuntu:bionic FLAVORS=rust-stable COMBINE='rust-stable;jdk-8,jdk-11,jdk-16'
    - BASE_IMAGE=ubuntu:bionic FLAVORS=rust-nightly COMBINE='rust-nightly;jdk-8,jdk-11,jdk-16'
    - BASE_IMAGE=ubuntu:bionic FLAVORS=rust-nightly-2020-04-22 COMBINE='rust-nightly-2020-04-22;jdk-8,jdk-11,jdk-16'
    - BASE_IMAGE=ubuntu:bionic FLAVORS=rust-nightly-2021-04-25 COMBINE='rust-nightly-2021-04-25;jdk-8,jdk-11,jdk-16'
    - BASE_IMAGE=ubuntu:bionic FLAVORS=jdk-8,jdk-11,jdk-16
    - BASE_IMAGE=ubuntu:focal FLAVORS=rust-1.42.0 COMBINE='rust-1.42.0;jdk-8,jdk-11,jdk-16'
    - BASE_IMAGE=ubuntu:focal FLAVORS=rust-1.51.0 COMBINE='rust-1.51.0;jdk-8,jdk-11,jdk-16'
    - BASE_IMAGE=ubuntu:focal FLAVORS=rust-stable COMBINE='rust-stable;jdk-8,jdk-11,jdk-16'
    - BASE_IMAGE=ubuntu:focal FLAVORS=rust-nightly COMBINE='rust-nightly;jdk-8,jdk-11,jdk-16'
    - BASE_IMAGE=ubuntu:focal FLAVORS=rust-nightly-2020-04-22 COMBINE='rust-nightly-2020-04-22;jdk-8,jdk-11,jdk-16'
    - BASE_IMAGE=ubuntu:focal FLAVORS=rust-nightly-2021-04-25 COMBINE='rust-nightly-2021-04-25;jdk-8,jdk-11,jdk-16'
    - BASE_IMAGE=ubuntu:focal FLAVORS=jdk-8,jdk-11,jdk-16
# disabled due to https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1916485
#    - BASE_IMAGE=ubuntu:hirsute FLAVORS=rust-stable COMBINE='rust-stable;jdk-8,jdk-11,jdk-16'
#    - BASE_IMAGE=ubuntu:hirsute FLAVORS=rust-nightly COMBINE='rust-nightly;jdk-8,jdk-11,jdk-16'
#    - BASE_IMAGE=ubuntu:hirsute FLAVORS=jdk-8,jdk-11,jdk-16
script: ci/script.sh
