name: Build

run-name: "Workflow CI/CD: build ci-base image(s)"

on:
  schedule:
    - cron: "0 1 * * SUN"  # Runs every Sunday 1:00 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # allow other matrix jobs to continue even if one fails
      matrix:
        include:
          # --- Single-flavor builds ---
          - base-image: ubuntu:jammy
            flavor: rust-stable
            combine: ""
          - base-image: ubuntu:jammy
            flavor: rust-nightly
            combine: ""

          - base-image: ubuntu:noble
            flavor: rust-stable
            combine: ""
          - base-image: ubuntu:noble
            flavor: rust-nightly
            combine: ""

          - base-image: debian:bullseye
            flavor: rust-stable
            combine: ""
          - base-image: debian:bullseye
            flavor: rust-nightly
            combine: ""

          - base-image: debian:bookworm
            flavor: rust-stable
            combine: ""
          - base-image: debian:bookworm
            flavor: rust-nightly
            combine: ""
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Docker image build
        env:
          BASE_IMAGE: ${{ matrix.base-image }}
          FLAVORS: ${{ matrix.flavor }}
          COMBINE: ${{ matrix.combine }}
          IMAGE_NAME: ci-base
          DOCKER_ORG: horizenlabs
          GOSU_VERSION: 1.19
          RUST_CROSS_TARGETS: "x86_64-pc-windows-gnu|wasm32-unknown-unknown"
          RUST_COMPONENTS: "rust-src|llvm-tools-preview"
          CARGO_AUDIT_VERSION_OLD_RUST: 0.16.0
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
        run: bash ${{ github.workspace }}/ci/script.sh

  # Slack notification if failed on scheduled run
  failure-notification:
    runs-on: ubuntu-latest
    name: Notify if failed
    needs: [build]
    if: ${{ failure() && !cancelled() && github.event_name == 'schedule' }}
    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@45a88b9581bfab2566dc881e2cd66d334e621e2c # v3.0.3
        with:
          webhook: ${{ secrets.SLACK_NOTIFY_WEBHOOK }}
          webhook-type: incoming-webhook
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "🚨 ALERT - ${{ github.workflow }} Job Failed! 🚨"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Job URL:* <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Job>"
                    }
                  ]
                }
              ]
            }
